---
- name: Manage AWS IAM Users
  hosts: localhost
  vars:
    user_list:
      - Suriya
      - Sridhar
      - Swapnil
      - Meenakshi
    dev_group: "DevGroup"
    admin_policy_arn: "arn:aws:iam::aws:policy/AdministratorAccess"

  tasks:
    # Step 1: Normalize usernames to ensure compliance with AWS rules
    - name: Normalize usernames
      set_fact:
        normalized_users: "{{ user_list | map('lower') | map('regex_replace', '[^\\w+=,.@-]', '-') | list }}"

    - name: Debug normalized user list
      debug:
        var: normalized_users

    # Step 2: Create IAM Users
    - name: Create IAM users
      amazon.aws.iam_user:
        name: "{{ item }}"
        state: present
      loop: "{{ normalized_users }}"

    # Step 3: Attach Admin Policy to Each User
    - name: Attach Admin policy to IAM users
      amazon.aws.iam_policy_attachment:
        name: "AdminPolicyAttachment-{{ item }}"
        users:
          - "{{ item }}"
        policy_arn: "{{ admin_policy_arn }}"
        state: present
      loop: "{{ normalized_users }}"

    # Step 4: Ensure the Dev Group Exists
    - name: Create or validate Dev group
      amazon.aws.iam_group:
        name: "{{ dev_group }}"
        state: present

    # Step 5: Add Users to Dev Group
    - name: Add IAM users to Dev group
      amazon.aws.iam_group_membership:
        name: "{{ dev_group }}"
        users: "{{ normalized_users }}"
        state: present
